%\VignetteIndexEntry{Trendy Vignette}
%\VignettePackage{Trendy}
%\VignetteEngine{knitr::knitr}

\documentclass{article}\usepackage[]{graphicx}\usepackage[usenames,dvipsnames]{color}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage{graphicx, graphics, epsfig,setspace,amsmath, amsthm}
\usepackage{natbib}
\usepackage{moreverb}
\usepackage{float}

\RequirePackage{/Library/Frameworks/R.framework/Versions/3.4/Resources/library/BiocStyle/resources/tex/Bioconductor}

\AtBeginDocument{\bibliographystyle{/Library/Frameworks/R.framework/Versions/3.4/Resources/library/BiocStyle/resources/tex/unsrturl}}


\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}

\title{Trendy: Segmented regression analysis of
expression dynamics for high-throughput ordered
profiling experimentsa}
\author{Rhonda Bacher, Ning Leng, Ron Stewart}
\maketitle
\tableofcontents
\setcounter{tocdepth}{2}



\section{Overview}
\label{sec:intro}
Trendy is an R package that can be used to perform breakpoint analysis on microarray or RNA-seq expression data with ordered conditions (e.g. time-course, spatial-course).
For each gene or other features, Trendy estimates the optimal number of breakpoints as well as
the breakpoints by fitting a set of segmented regression models.
The top dynamic genes are then identified by taking genes that can be well profiled by its gene-specific segmented regression model. Trendy also implements functions to visualize the dynamic genes and their trends, to order 
dynamic genes by their trends, and to compute breakpoint distribution at different
time-points (e.g. detect time-points with a large number of expression changes).

\subsection{The model}
To illustrate Trendy, here we use time course gene expression data as an example. 
Although, Trendy may also be applied to other types of features (e.g. isoform or exon expression) and/or other
types of experiments with ordered conditions (e.g. spatial course).

Denote the normalized gene expression of gene $g$ and sample/time $t$ as $Y_{g,t}$.
Denote the total number of genes as $G$ and the total number of samples/times as $N$.
For each gene, Trendy fits segmented regression models with varying numbers of breakpoints from 1 to $K$. $K$ defaults to 3 but can also
be specified by the user. The segmented R package is used to fit the segmented regression models.

For a given gene, among the models with varying $k$, Trendy selects the optimal
number of breakpoints for this gene by comparing the coefficient of determination ($R^2$) for each model.

To avoid overfitting, the optimal number of breakpoints will be set as
$\tilde{k_g} = \tilde{k_g} -1$ if any of the following happens:
at least one segment has less than $c_{num}$ samples
or $R^{2}_{g,\tilde{k_g}} - R^{2}_{g,\tilde{k_g}-1} < c_{diff}$. The thresholds
$c_{num}$ and $c_{diff}$ can be specified by the user; the 
defaults are 5 and 0.1,
respectively.


Trendy reports the following for the optimal model:
\begin{itemize}
  \item Gene specific adjusted $R^2$ (penalized for the chosen value of $k$)
  \item Segment slopes
  \item Breakpoint estimates
\end{itemize}

Among all genes, the top dynamic genes are defined as those whose optimal model has high adjusted $R^2$s.

To compute the breakpoint distribution over the time-course, Trendy calculates the number of 
breakpoints for each time-point across all the genes.

The time-points with high $D_t$ can be considered as those with global expression changes.

Trendy also summarizes the fitted trend or expression pattern of top genes. For samples between the $i^{th}$
and $i+1 ^{th}$ breakpoint for a given gene, if the t-statistic of
the segment slope has p-value greater than $c_{pval}$,
the trend of this segment will be defined as no change. Otherwise the
trend of this segment will be defined as up/down based on the slope coefficient.
The default value of $c_{pval}$ is 0.1, but may also be specified by the user.

\section{Installation}

\subsection{Install via GitHub}

The Trendy package can be installed using functions in the devtools package.

To install, type the following code into R:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{install.packages}\hlstd{(}\hlstr{"devtools"}\hlstd{)}
\hlkwd{library}\hlstd{(devtools)}
\hlkwd{install_github}\hlstd{(}\hlstr{"rhondabacher/Trendy/package/Trendy"}\hlstd{)}
\end{alltt}
\end{kframe}
\end{knitrout}

\subsection{Install locally}

Install packages segmented and gplots:


\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{install.packages}\hlstd{(}\hlkwd{c}\hlstd{(}\hlstr{"segmented"}\hlstd{,}\hlstr{"gplots"}\hlstd{))}
\hlkwd{library}\hlstd{(}\hlstr{"segmented"}\hlstd{)}
\hlkwd{library}\hlstd{(}\hlstr{"gplots"}\hlstd{)}
\end{alltt}
\end{kframe}
\end{knitrout}

Download the Trendy package from: \url{https://github.com/rhonda/Trendy/tree/master/package}

And install the package locally.


\subsection{Load the package}

To load the Trendy package:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{library}\hlstd{(Trendy)}
\end{alltt}
\end{kframe}
\end{knitrout}

\section{Analysis}

\subsection{Input}

The input data should be a $G-by-N$ matrix containing the expression values for each gene and
 each sample, where $G$ is the number of genes and $N$ is the number of samples. 
The samples should be sorted following the time course order.
These values should exhibit expression data after normalization across samples. 
For example, for RNA-seq data, the raw counts may be normalized using MedianNorm and
\Rfunction{GetNormalizedMat} function in \Biocpkg{EBSeq}. More details can be found in the \Biocpkg{EBSeq} vignette:

\url{http://www.bioconductor.org/packages/devel/bioc/vignettes/EBSeq/inst/doc/EBSeq_Vignette.pdf}


The object TrendyExData is a simulated data matrix containing 50 rows of genes and 40 columns of samples.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{data}\hlstd{(TrendyExData)}
\hlkwd{str}\hlstd{(TrendyExData)}
\end{alltt}
\begin{verbatim}
##  num [1:50, 1:40] 240 199 198 239 202 ...
##  - attr(*, "dimnames")=List of 2
##   ..$ : chr [1:50] "g1" "g2" "g3" "g4" ...
##   ..$ : chr [1:40] "s1" "s2" "s3" "s4" ...
\end{verbatim}
\end{kframe}
\end{knitrout}




\subsection{Run Trendy}

The \Rfunction{trendy} function will fit multiple segmented regressions model for each gene (via the \CRANpkg{segmented} R package) and select the the optimal model. Here we want to only consider a maximum of two breakpoints for each gene.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{res} \hlkwb{<-} \hlkwd{trendy}\hlstd{(TrendyExData,} \hlkwc{Max.K} \hlstd{=} \hlnum{2}\hlstd{)}
\hlstd{res.top} \hlkwb{<-} \hlkwd{toptrendy}\hlstd{(res)}
\hlcom{# default adjusted R square cutoff is 0.5}
\hlstd{res.top}\hlopt{$}\hlstd{radj}
\end{alltt}
\begin{verbatim}
##        g3        g1       g28       g20       g15        g2       g10       g23        g8 
## 0.9787382 0.9775005 0.9751380 0.9739715 0.9729747 0.9710139 0.9705118 0.9701402 0.9691341 
##        g5       g24       g17       g12       g29       g16       g22       g18       g25 
## 0.9689555 0.9656732 0.9652141 0.9644343 0.9632348 0.9630272 0.9627092 0.9626837 0.9611528 
##       g11       g30       g26        g7        g4        g9       g21        g6       g19 
## 0.9600736 0.9597989 0.9572072 0.9529077 0.9420853 0.9377311 0.9304116 0.9291045 0.9259893 
##       g27       g14       g13 
## 0.9183375 0.8656596 0.8576471
\end{verbatim}
\end{kframe}
\end{knitrout}

The \Rfunction{toptrendy} function may be used to extract top dynamic genes.
By default, \Rfunction{toptrendy} will extract genes whose adjusted $R^2$, $\bar{R}^{2}$,
is greater or equal to 0.5. To change this threshold, a user may specify the
\Rcode{AdjR.Cut} parameter in the \Rfunction{toptrendy} function.
res.top\$radj gives the $\bar{R}^{2}$ of the top dynamic genes sorted decreasingly.


By default the \Rfunction{trendy} function only considers genes whose mean expression is greater than 10. 
To use another threshold, the user may specify the parameter \Robject{Mean.Cut}.


\subsection{Visualize trends of the top dynamic genes}

res.top\$id.sign gives the trend specification of the top genes. The function \Rfunction{trendheatmap} can be used to display these trends:

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{res.trend} \hlkwb{<-} \hlkwd{trendheatmap}\hlstd{(res.top)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=.6\textwidth]{figure/unnamed-chunk-6-1} 

}


\begin{kframe}\begin{alltt}
\hlkwd{str}\hlstd{(res.trend)}
\end{alltt}
\begin{verbatim}
## List of 3
##  $ firstup      : Named num [1:17] 11.4 11.5 11.6 11.6 11.6 ...
##   ..- attr(*, "names")= chr [1:17] "g29" "g26" "g7" "g25" ...
##  $ firstdown    : Named num [1:11] 12.1 12.6 12.6 12.7 12.8 ...
##   ..- attr(*, "names")= chr [1:11] "g9" "g27" "g19" "g6" ...
##  $ firstnochange: Named num [1:2] 19 20.4
##   ..- attr(*, "names")= chr [1:2] "g28" "g5"
\end{verbatim}
\end{kframe}
\end{knitrout}

The \Rfunction{trendheatmap} function classifies the top dynamic genes into
three groups: start with up, start with down and start with no change.
Within each group, genes are sorted by the position of the first breakpoint.


To generate an expression heatmap of the first group of genes (first go up):

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{library}\hlstd{(gplots)}
\hlkwd{heatmap.2}\hlstd{(TrendyExData[}\hlkwd{names}\hlstd{(res.trend}\hlopt{$}\hlstd{firstup),],}
  \hlkwc{trace}\hlstd{=}\hlstr{"none"}\hlstd{,} \hlkwc{Rowv}\hlstd{=F,}\hlkwc{Colv}\hlstd{=F,}
        \hlkwc{scale}\hlstd{=}\hlstr{"row"}\hlstd{,} \hlkwc{main}\hlstd{=}\hlstr{"top genes (first go up)"}\hlstd{)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=.8\textwidth]{figure/unnamed-chunk-7-1} 

}



\end{knitrout}


Similarly, to generate an expression heatmap of the second group of genes (first go down):
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{heatmap.2}\hlstd{(TrendyExData[}\hlkwd{names}\hlstd{(res.trend}\hlopt{$}\hlstd{firstdown),],}
  \hlkwc{trace}\hlstd{=}\hlstr{"none"}\hlstd{,} \hlkwc{Rowv}\hlstd{=F,}\hlkwc{Colv}\hlstd{=F,}
        \hlkwc{scale}\hlstd{=}\hlstr{"row"}\hlstd{,} \hlkwc{main}\hlstd{=}\hlstr{"top genes (first go down)"}\hlstd{)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=.8\textwidth]{figure/unnamed-chunk-8-1} 

}



\end{knitrout}

To generate an expression heatmap of the second group of genes (first no change):
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{heatmap.2}\hlstd{(TrendyExData[}\hlkwd{names}\hlstd{(res.trend}\hlopt{$}\hlstd{firstnochange),],}
  \hlkwc{trace}\hlstd{=}\hlstr{"none"}\hlstd{,} \hlkwc{Rowv}\hlstd{=F,}\hlkwc{Colv}\hlstd{=F,}
        \hlkwc{scale}\hlstd{=}\hlstr{"row"}\hlstd{,} \hlkwc{main}\hlstd{=}\hlstr{"top genes (first no change)"}\hlstd{,}
        \hlkwc{cexRow}\hlstd{=}\hlnum{.8}\hlstd{)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=.8\textwidth]{figure/unnamed-chunk-9-1} 

}



\end{knitrout}


\subsection{Visualize individual genes}
The \Rfunction{plotfeature} function may be used to plot expression of individual features/genes and the fitted lines.

For example, to plot the top six genes in the first group of genes (first go up):

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{par}\hlstd{(}\hlkwc{mfrow}\hlstd{=}\hlkwd{c}\hlstd{(}\hlnum{3}\hlstd{,}\hlnum{2}\hlstd{))}
\hlstd{plot1} \hlkwb{<-} \hlkwd{plotfeature}\hlstd{(TrendyExData,}
                    \hlkwc{Feature.Names} \hlstd{=} \hlkwd{names}\hlstd{(res.trend}\hlopt{$}\hlstd{firstup)[}\hlnum{1}\hlopt{:}\hlnum{6}\hlstd{],}
                    \hlkwc{Seg.Data} \hlstd{= res)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=1\textwidth]{figure/unnamed-chunk-10-1} 

}



\end{knitrout}

The input of function \Rfunction{plotfeature} requires the expression data and a list of genes of interest.
The parameter \Robject{Seg.Data} results from the \Rfunction{trendy} function.
If it is not specified, then \Rfunction{plotfeature} will run \Rfunction{trendy} on the genes of interest before plotting.
Specifying the fitted results obtained from previous steps will save time by avoiding fitting the models again.

Similarly, to plot the top six genes in the second group of genes (first go down):

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{par}\hlstd{(}\hlkwc{mfrow}\hlstd{=}\hlkwd{c}\hlstd{(}\hlnum{3}\hlstd{,}\hlnum{2}\hlstd{))}
\hlstd{plot2} \hlkwb{<-} \hlkwd{plotfeature}\hlstd{(TrendyExData,}
                    \hlkwc{Feature.Names} \hlstd{=} \hlkwd{names}\hlstd{(res.trend}\hlopt{$}\hlstd{firstdown)[}\hlnum{1}\hlopt{:}\hlnum{6}\hlstd{],}
                    \hlkwc{Seg.Data} \hlstd{= res)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=1\textwidth]{figure/unnamed-chunk-11-1} 

}



\end{knitrout}

To plot the two genes in the third group of genes (first no change):
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{par}\hlstd{(}\hlkwc{mfrow}\hlstd{=}\hlkwd{c}\hlstd{(}\hlnum{1}\hlstd{,}\hlnum{2}\hlstd{))}
\hlstd{plot2} \hlkwb{<-} \hlkwd{plotfeature}\hlstd{(TrendyExData,}
                    \hlkwc{Feature.Names} \hlstd{=} \hlkwd{names}\hlstd{(res.trend}\hlopt{$}\hlstd{firstnochange)[}\hlnum{1}\hlopt{:}\hlnum{2}\hlstd{],}
                    \hlkwc{Seg.Data} \hlstd{= res)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=\maxwidth]{figure/unnamed-chunk-12-1} 

}



\end{knitrout}

\subsection{Gene specific estimates}

For a given gene of interest, its estimated parameters can be obtained by (using g2 as an example):
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{par}\hlstd{(}\hlkwc{mfrow}\hlstd{=}\hlkwd{c}\hlstd{(}\hlnum{1}\hlstd{,}\hlnum{1}\hlstd{))}
\hlstd{plot2} \hlkwb{<-} \hlkwd{plotfeature}\hlstd{(TrendyExData,}
                    \hlkwc{Feature.Names} \hlstd{=} \hlstr{"g2"}\hlstd{,}
                    \hlkwc{Seg.Data} \hlstd{= res)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=\maxwidth]{figure/unnamed-chunk-13-1} 

}


\begin{kframe}\begin{alltt}
\hlkwd{print}\hlstd{(res.top}\hlopt{$}\hlstd{bp[}\hlstr{"g2"}\hlstd{])} \hlcom{# break points}
\end{alltt}
\begin{verbatim}
## $g2
## breakpoint1 breakpoint2 
##    12.47356    30.14908
\end{verbatim}
\begin{alltt}
\hlkwd{print}\hlstd{(res.top}\hlopt{$}\hlstd{radj[}\hlstr{"g2"}\hlstd{])} \hlcom{# adjusted r squared}
\end{alltt}
\begin{verbatim}
##        g2 
## 0.9710139
\end{verbatim}
\begin{alltt}
\hlkwd{print}\hlstd{(res.top}\hlopt{$}\hlstd{slp[}\hlstr{"g2"}\hlstd{])} \hlcom{# fitted slopes of the segments}
\end{alltt}
\begin{verbatim}
## $g2
##  slope1  slope2  slope3 
##  3.3110  0.0607 -2.9730
\end{verbatim}
\begin{alltt}
\hlkwd{print}\hlstd{(res.top}\hlopt{$}\hlstd{slp.pval[}\hlstr{"g2"}\hlstd{])} \hlcom{# p value of each the segment}
\end{alltt}
\begin{verbatim}
## $g2
##      pval1      pval2      pval3 
## 0.01669386 0.31815050 0.02445599
\end{verbatim}
\end{kframe}
\end{knitrout}

The above printouts show that for gene g2 the optimal number of breakpoints
is 2. Two estimated breakpoints are around time-points s12 and s30.
The fitted slopes for the 3 segments are 3.31, 0.06 and -2.97, which indicate the trend is up-same-down.


These estimates can also be automatically formatted using the function \Rfunction{formatresults} 
which can be saved as a .txt. or .csv file. The output currently includes the estimate slope of 
each segment, the estimated breakpoint, and the adjusted $R^2$.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{trendy.summary} \hlkwb{<-} \hlkwd{formatresults}\hlstd{(res.top)}
\hlkwd{head}\hlstd{(trendy.summary)}
\end{alltt}
\begin{verbatim}
##     feature   slope1    slope2 slope3 breakpoint1 breakpoint2     adjR2
## g3       g3  1.57200 -2.548000     NA    26.97696          NA 0.9787382
## g1       g1 -3.14500  0.001548     NA    13.76450          NA 0.9775005
## g28     g28 -0.01381  1.537000     NA    19.00675          NA 0.9751380
## g20     g20 -3.38100 -0.082460     NA    12.80019          NA 0.9739715
## g15     g15  1.67500 -2.471000     NA    26.31814          NA 0.9729747
## g2       g2  3.31100  0.060700 -2.973    12.47356    30.14908 0.9710139
\end{verbatim}
\begin{alltt}
\hlcom{# write.table(trendy.summary, file="trendy_summary.txt")}
\end{alltt}
\end{kframe}
\end{knitrout}
The NA indicates that g3 does not have a slope3 since it only has one breakpoint (i.e two segments).


\subsection{Breakpoint distribution over the time course}

To calculate number of breakpoints over the time course:

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{res.bp} \hlkwb{<-} \hlkwd{bpdist}\hlstd{(res.top)}
\hlkwd{barplot}\hlstd{(res.bp,} \hlkwc{ylab}\hlstd{=}\hlstr{"Number of breakpoint"}\hlstd{,} \hlkwc{col}\hlstd{=}\hlstr{"blue"}\hlstd{)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=.8\textwidth]{figure/unnamed-chunk-15-1} 

}



\end{knitrout}

The bar plot indicates that a number of genes have breakpoints around s12 and s13.

\section{More advanced analysis}

\subsection{Time course with non-uniform sampling}
If the samples were collected with different time intervals and the user wants to
use the original time (instead of a vector of consecutive numbers),
the user may specify it via the T.Vect parameter in the \Rfunction{trendy} function.

For example, suppose for the example data, the first 30 samples were collected
every hour and the other 10 samples were collected every 5 hours. We may define
the time vector as:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{t.v} \hlkwb{<-} \hlkwd{c}\hlstd{(}\hlnum{1}\hlopt{:}\hlnum{30}\hlstd{,}\hlkwd{seq}\hlstd{(}\hlnum{31}\hlstd{,}\hlnum{80}\hlstd{,}\hlnum{5}\hlstd{))}
\hlkwd{names}\hlstd{(t.v)} \hlkwb{<-} \hlkwd{colnames}\hlstd{(TrendyExData)}
\hlkwd{print}\hlstd{(t.v)}
\end{alltt}
\begin{verbatim}
##  s1  s2  s3  s4  s5  s6  s7  s8  s9 s10 s11 s12 s13 s14 s15 s16 s17 s18 s19 s20 s21 s22 
##   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22 
## s23 s24 s25 s26 s27 s28 s29 s30 s31 s32 s33 s34 s35 s36 s37 s38 s39 s40 
##  23  24  25  26  27  28  29  30  31  36  41  46  51  56  61  66  71  76
\end{verbatim}
\end{kframe}
\end{knitrout}

To run Trendy model using the empirical collecting time instead of sample ID (1-40):

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{res2} \hlkwb{<-} \hlkwd{trendy}\hlstd{(TrendyExData,} \hlkwc{T.Vect}\hlstd{=t.v,} \hlkwc{Max.K}\hlstd{=}\hlnum{2}\hlstd{,} \hlkwc{Cut.Diff}\hlstd{=}\hlnum{.05}\hlstd{)}
\hlstd{res.top2} \hlkwb{<-} \hlkwd{toptrendy}\hlstd{(res2)}
\hlstd{res.trend2} \hlkwb{<-} \hlkwd{trendheatmap}\hlstd{(res.top2)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=.8\textwidth]{figure/unnamed-chunk-17-1} 

}


\begin{kframe}\begin{alltt}
\hlkwd{str}\hlstd{(res.trend2)}
\end{alltt}
\begin{verbatim}
## List of 3
##  $ firstup      : Named num [1:17] 11.4 11.4 11.6 11.7 12 ...
##   ..- attr(*, "names")= chr [1:17] "g29" "g8" "g26" "g7" ...
##  $ firstdown    : Named num [1:11] 11 11.2 11.3 11.4 11.4 ...
##   ..- attr(*, "names")= chr [1:11] "g9" "g19" "g21" "g4" ...
##  $ firstnochange: Named num [1:2] 19 19.5
##   ..- attr(*, "names")= chr [1:2] "g28" "g5"
\end{verbatim}
\end{kframe}
\end{knitrout}

To plot the first six genes that have up-regulated pattern at the beginning of the time course:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{par}\hlstd{(}\hlkwc{mfrow}\hlstd{=}\hlkwd{c}\hlstd{(}\hlnum{3}\hlstd{,}\hlnum{2}\hlstd{))}
\hlstd{plot1.new} \hlkwb{<-} \hlkwd{plotfeature}\hlstd{(TrendyExData,} \hlkwc{T.Vect}\hlstd{=t.v,}
                        \hlkwc{Feature.Names} \hlstd{=} \hlkwd{names}\hlstd{(res.trend2}\hlopt{$}\hlstd{firstup)[}\hlnum{1}\hlopt{:}\hlnum{6}\hlstd{],}
                        \hlkwc{Seg.Data} \hlstd{= res2)}
\end{alltt}
\end{kframe}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-18-1} 

\end{knitrout}



\section{Extract genes with certain pattern}
Genes that have a peak along the time-course will have fitted trend somewhere as "up-down". Genes that are oscillating may have the fitted trend "up-down-up-down". To extract a list of such genes we can use the \Rfunction{extractpattern}:

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# Genes that peak}
\hlstd{pat1} \hlkwb{<-} \hlkwd{extractpattern}\hlstd{(res2,} \hlkwc{Pattern} \hlstd{=} \hlkwd{c}\hlstd{(}\hlstr{"up"}\hlstd{,}\hlstr{"down"}\hlstd{))}
\hlkwd{head}\hlstd{(pat1)}
\end{alltt}
\begin{verbatim}
##    Gene BreakPoint1
## 3   g29    11.35849
## 1    g8    11.43482
## 8   g26    11.56147
## 12   g7    11.65663
## 2   g11    11.99780
## 4   g30    12.38463
\end{verbatim}
\begin{alltt}
\hlkwd{par}\hlstd{(}\hlkwc{mfrow}\hlstd{=}\hlkwd{c}\hlstd{(}\hlnum{3}\hlstd{,}\hlnum{2}\hlstd{))}
\hlstd{plotPat1} \hlkwb{<-} \hlkwd{plotfeature}\hlstd{(TrendyExData,} \hlkwc{T.Vect}\hlstd{=t.v,}
                      \hlkwc{Feature.Names} \hlstd{= pat1}\hlopt{$}\hlstd{Gene[}\hlnum{1}\hlopt{:}\hlnum{6}\hlstd{],}
                      \hlkwc{Seg.Data} \hlstd{= res2)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=.8\textwidth]{figure/unnamed-chunk-19-1} 

}



\end{knitrout}

% # <<eval=TRUE, warning=FALSE, fig.height=7, fig.width=7, fig.align='center', out.width='.8\\textwidth'>>=
% # # Genes that oscillate
% # pat1 <- extractpattern(res3, Pattern = c("up","down","up","down"))
% # @

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# Genes that peak after some time}
\hlstd{pat3} \hlkwb{<-} \hlkwd{extractpattern}\hlstd{(res2,} \hlkwc{Pattern} \hlstd{=} \hlkwd{c}\hlstd{(}\hlstr{"up"}\hlstd{,}\hlstr{"down"}\hlstd{),} \hlkwc{Delay} \hlstd{=} \hlnum{25}\hlstd{)}
\hlkwd{head}\hlstd{(pat3)}
\end{alltt}
\begin{verbatim}
##   Gene BreakPoint1
## 2  g22    25.01831
## 1   g3    25.43516
\end{verbatim}
\begin{alltt}
\hlkwd{par}\hlstd{(}\hlkwc{mfrow}\hlstd{=}\hlkwd{c}\hlstd{(}\hlnum{1}\hlstd{,}\hlnum{2}\hlstd{))}
\hlstd{plotPat3} \hlkwb{<-} \hlkwd{plotfeature}\hlstd{(TrendyExData,} \hlkwc{T.Vect}\hlstd{=t.v,}
                      \hlkwc{Feature.Names} \hlstd{= pat3}\hlopt{$}\hlstd{Gene,}
                      \hlkwc{Seg.Data} \hlstd{= res2)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=.8\textwidth]{figure/unnamed-chunk-20-1} 

}



\end{knitrout}


\section{Additional options}
In the \Rfunction{trendy} function,
the thresholds $c_{num}$, $c_{diff}$ and  $c_{pval}$
can be specified via parameters
Min.Num.In.Seg, Cut.Diff and Pval.Cut, respectively.

\section{Trendy shiny app}

The Trendy shiny app requires an .RData object output from the \Rfunction{trendy} function, which can be obtained by setting \Rcode{Save.Object=TRUE}.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{res} \hlkwb{<-} \hlkwd{trendy}\hlstd{(TrendyExData,} \hlkwc{Max.K}\hlstd{=}\hlnum{2}\hlstd{,} \hlkwc{Save.Object} \hlstd{=} \hlnum{TRUE}\hlstd{,} \hlkwc{File.Name}\hlstd{=}\hlstr{"exampleObject"}\hlstd{)}
\end{alltt}
\end{kframe}
\end{knitrout}

Then in R run:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{library}\hlstd{(shiny)}
\hlkwd{runGitHub}\hlstd{(}\hlstr{'rhondabacher/Trendy'}\hlstd{)}
\end{alltt}
\end{kframe}
\end{knitrout}

\begin{figure}[H]
\centering
\includegraphics[width=1\textwidth]{Shiny_UploadData.png}
\caption{Upload shiny object}
\end{figure}


\begin{figure}[H]
\centering
\includegraphics[width=1\textwidth]{Shing_allGenePat.png}
\caption{Find all genes with a given pattern}
\end{figure}


\begin{figure}[H]
\centering
\includegraphics[width=1\textwidth]{Shiny_geneSearch.png}
\caption{Search genes individually}
\end{figure}

\newpage
\section{SessionInfo}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{print}\hlstd{(}\hlkwd{sessionInfo}\hlstd{())}
\end{alltt}
\begin{verbatim}
## R version 3.4.1 (2017-06-30)
## Platform: x86_64-apple-darwin15.6.0 (64-bit)
## Running under: OS X El Capitan 10.11.6
## 
## Matrix products: default
## BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
## LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib
## 
## locale:
## [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] gplots_3.0.1  Trendy_0.99.0 knitr_1.16   
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_0.12.12       gtools_3.5.0       digest_0.6.12      rprojroot_1.2     
##  [5] bitops_1.0-6       backports_1.1.0    magrittr_1.5       evaluate_0.10.1   
##  [9] KernSmooth_2.23-15 highr_0.6          stringi_1.1.5      gdata_2.18.0      
## [13] rmarkdown_1.6      BiocStyle_2.4.1    tools_3.4.1        stringr_1.2.0     
## [17] parallel_3.4.1     yaml_2.1.14        compiler_3.4.1     segmented_0.5-2.1 
## [21] caTools_1.17.1     htmltools_0.3.6
\end{verbatim}
\end{kframe}
\end{knitrout}






\end{document}
